version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      microsoft-aspnetcore:
        patterns:
          - "Microsoft.AspNetCore.*"
      microsoft-identitymodel:
        patterns:
          - "Microsoft.IdentityModel.*"
          - "System.IdentityModel.Tokens.Jwt"
      npgsql:
        patterns:
          - "Npgsql*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
