/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as AuthedLicencesRouteImport } from './routes/_authed/licences'
import { Route as AuthedLicencesIdRouteImport } from './routes/_authed/licences.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLicencesRoute = AuthedLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLicencesIdRoute = AuthedLicencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedLicencesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/licences': typeof AuthedLicencesRouteWithChildren
  '/me': typeof AuthedMeRoute
  '/products': typeof AuthedProductsRoute
  '/users': typeof AuthedUsersRoute
  '/licences/$id': typeof AuthedLicencesIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/licences': typeof AuthedLicencesRouteWithChildren
  '/me': typeof AuthedMeRoute
  '/products': typeof AuthedProductsRoute
  '/users': typeof AuthedUsersRoute
  '/': typeof AuthedIndexRoute
  '/licences/$id': typeof AuthedLicencesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/licences': typeof AuthedLicencesRouteWithChildren
  '/_authed/me': typeof AuthedMeRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/licences/$id': typeof AuthedLicencesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/licences'
    | '/me'
    | '/products'
    | '/users'
    | '/licences/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/licences'
    | '/me'
    | '/products'
    | '/users'
    | '/'
    | '/licences/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/licences'
    | '/_authed/me'
    | '/_authed/products'
    | '/_authed/users'
    | '/_authed/'
    | '/_authed/licences/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/licences': {
      id: '/_authed/licences'
      path: '/licences'
      fullPath: '/licences'
      preLoaderRoute: typeof AuthedLicencesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/licences/$id': {
      id: '/_authed/licences/$id'
      path: '/$id'
      fullPath: '/licences/$id'
      preLoaderRoute: typeof AuthedLicencesIdRouteImport
      parentRoute: typeof AuthedLicencesRoute
    }
  }
}

interface AuthedLicencesRouteChildren {
  AuthedLicencesIdRoute: typeof AuthedLicencesIdRoute
}

const AuthedLicencesRouteChildren: AuthedLicencesRouteChildren = {
  AuthedLicencesIdRoute: AuthedLicencesIdRoute,
}

const AuthedLicencesRouteWithChildren = AuthedLicencesRoute._addFileChildren(
  AuthedLicencesRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedLicencesRoute: typeof AuthedLicencesRouteWithChildren
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedLicencesRoute: AuthedLicencesRouteWithChildren,
  AuthedMeRoute: AuthedMeRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
