/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalProductsRouteImport } from './routes/portal/products'
import { Route as PortalOrdersRouteImport } from './routes/portal/orders'
import { Route as PortalMeRouteImport } from './routes/portal/me'
import { Route as PortalLicencesRouteImport } from './routes/portal/licences'
import { Route as PortalCheckoutRouteImport } from './routes/portal/checkout'
import { Route as PortalBasketRouteImport } from './routes/portal/basket'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMeRouteImport } from './routes/admin/me'
import { Route as AdminLicencesRouteImport } from './routes/admin/licences'
import { Route as PortalOrdersIdRouteImport } from './routes/portal/orders_.$id'
import { Route as PortalLicencesIdRouteImport } from './routes/portal/licences_.$id'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users_.new'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users_.$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products_.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders_.$id'
import { Route as AdminLicencesNewRouteImport } from './routes/admin/licences_.new'
import { Route as AdminLicencesIdRouteImport } from './routes/admin/licences_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMeRoute = PortalMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLicencesRoute = PortalLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalCheckoutRoute = PortalCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBasketRoute = PortalBasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMeRoute = AdminMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLicencesRoute = AdminLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalOrdersIdRoute = PortalOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLicencesIdRoute = PortalLicencesIdRouteImport.update({
  id: '/licences_/$id',
  path: '/licences/$id',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLicencesNewRoute = AdminLicencesNewRouteImport.update({
  id: '/licences_/new',
  path: '/licences/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLicencesIdRoute = AdminLicencesIdRouteImport.update({
  id: '/licences_/$id',
  path: '/licences/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/licences': typeof AdminLicencesRoute
  '/admin/me': typeof AdminMeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/licences': typeof PortalLicencesRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/licences/$id': typeof AdminLicencesIdRoute
  '/admin/licences/new': typeof AdminLicencesNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/portal/licences/$id': typeof PortalLicencesIdRoute
  '/portal/orders/$id': typeof PortalOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/licences': typeof AdminLicencesRoute
  '/admin/me': typeof AdminMeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/licences': typeof PortalLicencesRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/licences/$id': typeof AdminLicencesIdRoute
  '/admin/licences/new': typeof AdminLicencesNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/portal/licences/$id': typeof PortalLicencesIdRoute
  '/portal/orders/$id': typeof PortalOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/licences': typeof AdminLicencesRoute
  '/admin/me': typeof AdminMeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/basket': typeof PortalBasketRoute
  '/portal/checkout': typeof PortalCheckoutRoute
  '/portal/licences': typeof PortalLicencesRoute
  '/portal/me': typeof PortalMeRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/products': typeof PortalProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/licences_/$id': typeof AdminLicencesIdRoute
  '/admin/licences_/new': typeof AdminLicencesNewRoute
  '/admin/orders_/$id': typeof AdminOrdersIdRoute
  '/admin/products_/$id': typeof AdminProductsIdRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/portal/licences_/$id': typeof PortalLicencesIdRoute
  '/portal/orders_/$id': typeof PortalOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/forgot-password'
    | '/login'
    | '/admin/licences'
    | '/admin/me'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/licences'
    | '/portal/me'
    | '/portal/orders'
    | '/portal/products'
    | '/admin/'
    | '/portal/'
    | '/admin/licences/$id'
    | '/admin/licences/new'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/portal/licences/$id'
    | '/portal/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin/licences'
    | '/admin/me'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/licences'
    | '/portal/me'
    | '/portal/orders'
    | '/portal/products'
    | '/admin'
    | '/portal'
    | '/admin/licences/$id'
    | '/admin/licences/new'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/portal/licences/$id'
    | '/portal/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/forgot-password'
    | '/login'
    | '/admin/licences'
    | '/admin/me'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/portal/basket'
    | '/portal/checkout'
    | '/portal/licences'
    | '/portal/me'
    | '/portal/orders'
    | '/portal/products'
    | '/admin/'
    | '/portal/'
    | '/admin/licences_/$id'
    | '/admin/licences_/new'
    | '/admin/orders_/$id'
    | '/admin/products_/$id'
    | '/admin/products_/new'
    | '/admin/users_/$id'
    | '/admin/users_/new'
    | '/portal/licences_/$id'
    | '/portal/orders_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/me': {
      id: '/portal/me'
      path: '/me'
      fullPath: '/portal/me'
      preLoaderRoute: typeof PortalMeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/licences': {
      id: '/portal/licences'
      path: '/licences'
      fullPath: '/portal/licences'
      preLoaderRoute: typeof PortalLicencesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/checkout': {
      id: '/portal/checkout'
      path: '/checkout'
      fullPath: '/portal/checkout'
      preLoaderRoute: typeof PortalCheckoutRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/basket': {
      id: '/portal/basket'
      path: '/basket'
      fullPath: '/portal/basket'
      preLoaderRoute: typeof PortalBasketRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/me': {
      id: '/admin/me'
      path: '/me'
      fullPath: '/admin/me'
      preLoaderRoute: typeof AdminMeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/licences': {
      id: '/admin/licences'
      path: '/licences'
      fullPath: '/admin/licences'
      preLoaderRoute: typeof AdminLicencesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/orders_/$id': {
      id: '/portal/orders_/$id'
      path: '/orders/$id'
      fullPath: '/portal/orders/$id'
      preLoaderRoute: typeof PortalOrdersIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/licences_/$id': {
      id: '/portal/licences_/$id'
      path: '/licences/$id'
      fullPath: '/portal/licences/$id'
      preLoaderRoute: typeof PortalLicencesIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/$id': {
      id: '/admin/products_/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders_/$id': {
      id: '/admin/orders_/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/licences_/new': {
      id: '/admin/licences_/new'
      path: '/licences/new'
      fullPath: '/admin/licences/new'
      preLoaderRoute: typeof AdminLicencesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/licences_/$id': {
      id: '/admin/licences_/$id'
      path: '/licences/$id'
      fullPath: '/admin/licences/$id'
      preLoaderRoute: typeof AdminLicencesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLicencesRoute: typeof AdminLicencesRoute
  AdminMeRoute: typeof AdminMeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLicencesIdRoute: typeof AdminLicencesIdRoute
  AdminLicencesNewRoute: typeof AdminLicencesNewRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLicencesRoute: AdminLicencesRoute,
  AdminMeRoute: AdminMeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLicencesIdRoute: AdminLicencesIdRoute,
  AdminLicencesNewRoute: AdminLicencesNewRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalBasketRoute: typeof PortalBasketRoute
  PortalCheckoutRoute: typeof PortalCheckoutRoute
  PortalLicencesRoute: typeof PortalLicencesRoute
  PortalMeRoute: typeof PortalMeRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalLicencesIdRoute: typeof PortalLicencesIdRoute
  PortalOrdersIdRoute: typeof PortalOrdersIdRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalBasketRoute: PortalBasketRoute,
  PortalCheckoutRoute: PortalCheckoutRoute,
  PortalLicencesRoute: PortalLicencesRoute,
  PortalMeRoute: PortalMeRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalLicencesIdRoute: PortalLicencesIdRoute,
  PortalOrdersIdRoute: PortalOrdersIdRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
